version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.7
        environment:
          MIX_ENV: test
    working_directory: ~/repo
    steps:
      - checkout
      - run: epmd -daemon
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - run: mix deps.get
      - run: mix format --check-formatted --check-equivalent
      - run: mix dialyze
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
